title:              Begen Yussupov
email:              begen.ys@gmail.com
phone:              '571.595.7046'
description:        Data Scientist and Creator
author:             Begen Yussupov
baseurl:            ""
url:                "https://begen.github.io"

# Social Profiles
twitter_username:   
github_username:   https://github.com/begen 
facebook_username: 
instagram_username: https://www.instagram.com/benserzhan/
linkedin_username:  www.linkedin.com/in/begen-yussupov

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
